CREATE DATABASE {YOUR_DATABASE}
  WITH OWNER = {YOUR_ADMIN_USER}
       ENCODING = 'UTF8'
       LC_COLLATE = 'C'
       LC_CTYPE = 'C'
       TEMPLATE = template0
       CONNECTION LIMIT = -1;

CREATE ROLE {YOUR_USER} LOGIN PASSWORD 'YOUR_PASSWORD'
  NOSUPERUSER INHERIT NOCREATEDB NOCREATEROLE NOREPLICATION;
